### ISSUE TITLE
ERROR: No matching distribution found for angr==9.2.5.dev0

### ISSUE THREAD

**Issue by ice-tong** [angr/angr-dev#149] opened 2022-05-22 10:40 UTC
I got an install error when I ran the install command: `./setup.sh -i -e angr`
```
ERROR: Ignored the following versions that require a different python version: 7.8.9.26 Requires-Python <3.0
ERROR: Could not find a version that satisfies the requirement angr==9.2.5.dev0 (from angrop) (from versions: 0.8.0, 0.8.1, 4.5.9.9b0, 4.5.9.9, 4.5.9.13, 4.5.9.13.post1, 4.5.9.14, 4.5.9.22, 4.5.9.29, 4.5.10.14, 4.5.10.15, 4.5.11.23, 4.5.12.12, 4.5.12.21, 4.5.12.28, 4.6.1.4, 4.6.1.12, 4.6.1.18, 4.6.1.30, 4.6.2.25, 4.6.3.15, 4.6.3.15.post1, 4.6.3.18, 4.6.3.28, 4.6.4.28, 4.6.5.27, 4.6.5.27.post1, 4.6.6.4, 4.6.6.4.post1, 4.6.6.10, 4.6.6.15, 4.6.6.16, 4.6.6.28, 4.6.6.29, 5.6.8.22, 5.6.10.5, 5.6.10.7, 5.6.10.12, 5.6.12.3, 6.7.1.13, 6.7.1.13.post2, 6.7.1.31, 6.7.3.26, 6.7.4.12, 6.7.6.9, 6.7.7.27, 6.7.7.31, 7.7.9.8, 7.7.9.8.post1, 7.7.9.14, 7.7.9.21, 7.7.12.16, 7.8.2.21, 7.8.6.16, 7.8.6.23, 7.8.7.1, 7.8.8.1, 8.18.10.5, 8.18.10.25, 8.19.2.4, 8.19.4.5, 8.19.7.25, 8.19.10.29, 8.19.10.30, 8.20.1.7, 8.20.5.27, 8.20.6.1, 8.20.6.8, 8.20.7.6, 8.20.7.27, 9.0.4378, 9.0.4446, 9.0.4495, 9.0.4663, 9.0.4885, 9.0.4940, 9.0.5002, 9.0.5034, 9.0.5171, 9.0.5326, 9.0.5327, 9.0.5376, 9.0.5405, 9.0.5450, 9.0.5609, 9.0.5610, 9.0.5739, 9.0.5811, 9.0.5903, 9.0.6136, 9.0.6281, 9.0.6421, 9.0.6488, 9.0.6588, 9.0.6642, 9.0.6790, 9.0.6852, 9.0.6885, 9.0.7293, 9.0.7491, 9.0.7833, 9.0.7912, 9.0.8021, 9.0.8761, 9.0.9031, 9.0.9166, 9.0.9297, 9.0.9355, 9.0.9438, 9.0.9506, 9.0.9572, 9.0.9684, 9.0.9792, 9.0.9947, 9.0.10010, 9.0.10055, 9.0.10072, 9.0.10159, 9.0.10281, 9.0.10339, 9.0.10409, 9.0.10534, 9.0.10576, 9.0.10651, 9.0.10689, 9.0.10730, 9.1.10913, 9.1.11508, 9.1.11611, 9.1.11752, 9.1.12332, 9.2.1, 9.2.2, 9.2.3, 9.2.4)
ERROR: No matching distribution found for angr==9.2.5.dev0
[!!] pip failure (--no-build-isolation -e angrop). Check /tmp/setup-50845 for details, or read it here:
```
commit id: c4e422b08056a8625959589e8f3c17ee83e75e3e

Does it seem that angrop and angr-management are dependent on an invalid version of angr?

**Comment by rhelmot** [comment] 2022-05-22 14:59
angrop and angr-management intentionally depend on an invalid version of angr, to prevent mixing and matching git and pypi versions. Are you doing something which makes setup.sh install your dependencies in a weird order? By default, it should install all the invalid versions in the right order.

**Comment by Kyle-Kyle** [comment] 2022-05-22 17:45
@rhelmot this is an issue that started about 1 month ago, partially because of the pip isolation stuff. My current solution is to do the installation manually.
@ice-tong I don't have a good solution for now. But you can use `pip install -e --no-build-isolation .` in each sub-repo to make the installation work

**Comment by Kyle-Kyle** [comment] 2022-05-22 17:46
@twizmwazin shall we fix this?

**Comment by ice-tong** [comment] 2022-05-23 00:00
Thanks for reply.

I install success by comment
 angr dependency in setup.cfg for
 angrop and angr-management, but got import error in angrarch.

I think pip install angr is better for me.

**Comment by rhelmot** [comment] 2022-05-23 06:15
I still don't understand where the error is coming from, because we are [disabling build isolation](https://github.com/angr/angr-dev/commit/bea8f216627fb183d6dd97f9cfdcf783e5c11e14) for our pip install commands. When I clone angr-dev and run setup.sh in a fresh virtualenv, everything just works.

**Comment by Kyle-Kyle** [comment] 2022-05-23 07:45
I think I misunderstood the situation. isolation is disabled according to the posted output.

**Comment by twizmwazin** [comment] 2022-05-23 21:00
@ice-tong I would recommend using angr from PyPI if you are only planning to use it and not submit new patches. If you would like me to help debug this issue, if you can paste the output of `./git_all.sh show-ref HEAD` I can attempt to reproduce the issue.

**Comment by twizmwazin** [comment] 2022-05-27 23:56
Going to close this since I think the issue is solved, let me know if you'd like more help.

**Closed by twizmwazin** 2022-05-27 23:56 UTC
